Eviatar
iranroman/ZemlianovaRNN pull request #1
Opened 2024-10-31 22:43 UTC by evaisd

# Module helpers.py with the functions that do the analysis of the RNN.
# Script plot_fig5.py (self explanatory).
# Some Other additions/fixes:
1. Fixed single/double comma issue in train.py. 
2. Fixed the ZRNN to run without the Euler delta term during inference.
3. Added continuation_phase parameter to generate_stimuli that makes it generate null I_stim.
4. Some fixes in the ZRNN code - fixed devices compatibility issues and parameters names.

2024-11-01 13:09 UTC, iranroman commented on zrnn/datasets.py
> +def generate_stimuli(period, T_onset, duration=2.0, dt=0.001, one_dur=0.01, continuation_phase: bool = False):
I'd say we should change the name of this keyword argument from `continuation_phase` to `I_stim_without_clicks` and flip the boolean logic.

2024-11-01 13:12 UTC, iranroman commented
Thanks for this awesome work @evaisd . Please also make changes to the README to include the steps necessary to run this analysis.

2024-11-01 13:38 UTC, iranroman commented
This looks great overall. I left some minor comments, I might add more whenever I am able to run this to better understand the mechanics.  

Let's definitively add instructions to the README. Right now, for example, I just tried cloning the repo and running `python plot_fig5.py` but got this cryptic error. I'm sure I'm not following some appropriate step, but I have no way of knowing. 

```
ZemlianovaRNN % python plot_fig5.py
Traceback (most recent call last):
  File "/Users/iranroman/models/ZemlianovaRNN/plot_fig5.py", line 135, in <module>
    Fire(main)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/lib/python3.12/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/lib/python3.12/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/lib/python3.12/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iranroman/models/ZemlianovaRNN/plot_fig5.py", line 130, in main
    _plot_a(span=span, grid_length=grid_length)
  File "/Users/iranroman/models/ZemlianovaRNN/plot_fig5.py", line 44, in _plot_a
    im = _gen_single_plot(data, ax, span, grid_length, center_around_end_point=True)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iranroman/models/ZemlianovaRNN/plot_fig5.py", line 26, in _gen_single_plot
    end_point = (data['trajectory0'][-1], data['trajectory1'][-1])
                 ~~~~^^^^^^^^^^^^^^^
KeyError: 'trajectory0'
```

2024-11-01 14:54 UTC, iranroman commented
@kzemlianova please feel free to have a look and leave a review

2024-11-01 20:20 UTC, iranroman commented
@IamMarcIvanov (i.e. Danish) you too may leave a review

2024-11-01 22:31 UTC, evaisd commented
@iranroman I've got the issues fixed. Now it should run smoothly. It failed when you tried executing it because I left a flag I used to avoid repeating some steps during development. I updated the readme as well.

2024-11-04 22:09 UTC, iranroman requested changes
Thanks! I left a few more comments. In my view, this is almost there.

2024-11-04 22:09 UTC, iranroman commented on zrnn/helpers.py
> +#                      at_time: int = None) -> dict:
if this stuff in comments is not needed, let's delete it please.

2024-11-04 22:09 UTC, iranroman commented on zrnn/helpers.py
can we rename this as `utils.py` please?

2024-11-04 22:09 UTC, iranroman commented on zrnn/helpers.py
> +import pandas as pd
please add pandas to `requirements.txt`

2024-11-04 22:09 UTC, iranroman commented on README_figs/fig_5b.png
Wow, these figures are truly cool. 

One question: in this figure, is there a specific reason why you used timepoints that are different to those in the paper?

2024-11-04 22:09 UTC, iranroman commented on plot_fig5.py
can we add a progress bar or some sort of printing statement to let the user know what stage of the analysis we are at?

Also, running this I could not reproduce the qualitative features of the figures you provide. Granted, I was using a set of model weights I already had saved somewhere. Let me re-try from scratch running all pieces of code as you specify in this PR from the top of the README.

2024-11-04 22:09 UTC, iranroman commented on zrnn/helpers.py
@evaisd what do you think about this suggestion?

2024-11-04 22:10 UTC, iranroman commented on plot_fig5.py
Nevermind, I could! I may have been using an old set of `best_model.pth` weights.

2024-11-04 22:54 UTC, evaisd commented on zrnn/helpers.py
> +#                      at_time: int = None) -> dict:
Fixed in the more recent push.

2024-11-04 22:54 UTC, evaisd commented on zrnn/helpers.py
> +import pandas as pd
Added in the more recent push.

2024-11-04 23:25 UTC, evaisd commented on plot_fig5.py
Added progress statements.

2024-11-04 23:25 UTC, evaisd commented on README_figs/fig_5b.png
It's a combination of me mistaking the initial condition in this plot (in the paper they're not on the balance manifold as I did but on 0), which I have fixed, and the fact that in our simulation the flow seems to be a bit slower. In any case, I have reset the timepoints to be the same as in the paper.

2024-11-04 23:25 UTC, evaisd commented on zrnn/helpers.py
I don't mind, will rename it utils.

2024-11-05 10:52 UTC, iranroman approved these changes
Wow. Truly amazing work @evaisd I'm in awe. We are ready to merge. 

@kzemlianova and @IamMarcIvanov I encourage you to have a look.

2024-11-06 12:05 UTC, merged